Multiple fixes
TelosLabs/rails-world pull request #167
Opened 2024-09-05 23:06 UTC by AlanSoto31

## Description
- Update the Twitter logo.
- Make the last session card sticky.

## How has this been tested?

Please mark the tests that you ran to verify your changes. If difficult to test, consider providing instructions so reviewers can test.

- [x] Manual testing
- [ ] System tests
- [ ] Unit tests
- [ ] None

## Checklist

- [ ] CI pipeline is passing
- [ ] My code follows the conventions of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added seed data to the database (if applicable)

## Release tasks

Add any tasks that need to be done before/after the release of this feature.

## Screenshots/Loom

<img width="432" alt="image" src="https://github.com/user-attachments/assets/b2f92270-8837-4432-aab9-710be52909e4">
<img width="431" alt="image" src="https://github.com/user-attachments/assets/e7007b9b-ac71-4055-8342-bda4b9f7b081">
<img width="430" alt="image" src="https://github.com/user-attachments/assets/cc08bb3d-e0e7-4a8b-914c-604050b4f45d">

2024-09-10 20:37 UTC, andresag4 approved these changes

2024-09-11 17:43 UTC, LuigiR0jas requested changes
Do not merge yet.

2025-05-22 18:24 UTC, LuigiR0jas commented on app/views/schedules/show.html.erb
> +    <div class="flex flex-col w-full h-full mb-[50vh]">
```suggestion
    <div class="flex flex-col w-full h-full mb-[12rem]">
```

2025-05-22 18:24 UTC, LuigiR0jas commented on app/views/sessions/index.html.erb
> +    <div class="flex flex-col w-full h-full mb-[50vh]">
```suggestion
    <div class="flex flex-col w-full h-full mb-[12rem]">
```

2025-05-22 18:25 UTC, LuigiR0jas approved these changes

2025-05-22 18:45 UTC, merged