Feature | Update notification mailer
TelosLabs/rails-world pull request #91
Opened 2024-08-07 19:06 UTC by EdgarB

## Description

Please include a summary of the change. Also, include any additional information that you think is important for reviewers to know. Link to a related issue if applicable.

## How has this been tested?

Please mark the tests that you ran to verify your changes. If difficult to test, consider providing instructions so reviewers can test.

- [ ] Manual testing
- [ ] System tests
- [ ] Unit tests
- [ ] None

## Checklist

- [ ] CI pipeline is passing
- [ ] My code follows the conventions of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added seed data to the database (if applicable)

## Release tasks

Add any tasks that need to be done before/after the release of this feature.

## Screenshots/Loom

This section is relevant in case we want to share progress with the team, otherwise, it can be omitted.

2024-08-13 23:42 UTC, AlanSoto31 requested changes
The email looks odd

<img width="1033" alt="image" src="https://github.com/user-attachments/assets/c416c217-f0aa-470a-909a-d2800d6eb92e">

2024-08-13 23:42 UTC, AlanSoto31 commented on app/views/notifications_mailer/session_notification.html.erb
> +  <% end %>
The `title` method in the `SessionReminderNotifier` class might be useful for defining the title. If it doesn't fit the purpose, I suggest extracting this logic into the `SessionReminderNotifier` class to maintain consistency.

2024-08-15 02:11 UTC, AlanSoto31 requested changes

2024-08-15 22:46 UTC, AlanSoto31 approved these changes
Great work!

2024-08-16 01:50 UTC, Sergio-e requested changes
Don't merge. No changes are needed for the moment, I'll post them soon

2024-08-16 19:19 UTC, Sergio-e approved these changes

2024-08-16 19:21 UTC, merged